config/routes.rb
Rails.application.routes.draw do
  root 'time_zones#index'

  get 'time_zones/index'

  post 'time_zones/time'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/time_zones_controller.rb
class TimeZonesController < ApplicationController
  def index
    @array = [1, 2, 3, 4, 5]
  end

  def time
    @zone = params[:zone]
    @time = Time.now
    @time -= 1.hour if @zone == "Central"
    @time -= 2.hours if @zone == "Mountain"
    @time -= 3.hours if @zone == "Pacific"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_zones_helper.rb
module TimeZonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DateApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<p> Made by Cruz.  Don't h8.</p>
</body>
</html>

app/views/time_zones/index.html.erb
<h1>Enter your time zone</h1>

<%= form_tag time_zones_time_path do %>
  <%= select_tag :zone, options_for_select(["Eastern", "Central", "Mountain", "Pacific" ], "Eastern") %>
  <%= submit_tag "Get my time" %>
<% end %>


<ul>
  <% @array.each do |a| %>
    <li><%= a %></li>
  <% end %>
</ul>

app/views/time_zones/time.html.erb
<h1>You picked <%= @zone %></h1>

<p>The local time is: <%= @time.strftime("%B %e %Y") %></p>